---
- hosts: all
  become: true
  tasks: 
  
  - name: update repository index
    apt:
     update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]
  - name: install nginx package
    apt:
     name: nginx
     state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]
